### ISSUE TITLE
World is null - World loading lock

### ISSUE THREAD

**Issue by Ayuma-cell** [RandomMcSomethin/fallingleaves#29]
Getting locked up in World loading.

Using Quilt Modloader with several performance mods.
  [✔️] charm-fabric-1.18-4.1.0
  [✔️] charmonium-fabric-1.18-4.0.0
  [✔️] Chunky-1.2.164
  [✔️] CITResewn-1.0.1+1.18.2
  [✔️] cloth-config-6.2.57-fabric
  [✔️] cullleaves-2.3.2
  [✔️] dashloader-def-3.1.1+1.18
  [✔️] debugify-1.9.0-fabric-1.18.2
  [✔️] dynamic-fps-2.1.0
  [✔️] enhancedblockentities-0.6+1.18.2
  [✔️] entityculling-fabric-mc1.18-1.5.1
  [✔️] fallingleaves-1.11.0+1.18.2
  [✔️] FallingTree-1.18.2-3.5.1
  [✔️] ferritecore-4.2.1-fabric
  [✔️] indium-1.0.3+mc1.18.2
  [✔️] iris-mc1.18.2-1.2.4-build.38
  [✔️] krypton-0.1.9
  [✔️] Ksyxis-1.1
  [✔️] lazydfu-0.1.2
  [✔️] lithium-fabric-mc1.18.2-0.7.9
  [✔️] modmenu-3.2.1
  [✔️] pinglist-1.3.3
  [✔️] PresenceFootsteps-1.5.0
  [✔️] Quilt Standard Library 1.1.0 MC-1.18.2
  [✔️] reeses_sodium_options-mc1.18.2-1.4.2
  [✔️] servercore-1.2.9-1.18.2
  [✔️] sodium-extra-mc1.18.2-0.4.3
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  
`[11:20:15] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8406(net.minecraft.class_2394, double, double, double, double, double, double)" because "world" is null
	at randommcsomethin.fallingleaves.util.LeafUtil.spawnLeafParticles(LeafUtil.java:110) ~[fallingleaves-1.11.0+1.18.2.jar:?]
	at net.minecraft.class_2397.md33b1b4$lambda$randomTick$0$0(class_2397.java:1063) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.0-beta.16.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.0-beta.16.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28) [quilt-loader-0.16.0-beta.16.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23) [quilt-loader-0.16.0-beta.16.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:20:15] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8406(net.minecraft.class_2394, double, double, double, double, double, double)" because "world" is null
	at randommcsomethin.fallingleaves.util.LeafUtil.spawnLeafParticles(LeafUtil.java:110) ~[fallingleaves-1.11.0+1.18.2.jar:?]
	at net.minecraft.class_2397.md33b1b4$lambda$randomTick$0$0(class_2397.java:1063) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.0-beta.16.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.0-beta.16.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28) [quilt-loader-0.16.0-beta.16.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23) [quilt-loader-0.16.0-beta.16.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

**Comment by Fourmisain** [comment]
Oh, I see what's going on.
It's a super simple fix and it looks like this should be the only error of this kind.

Released a new version with the fix, [get it](https://modrinth.com/mod/fallingleaves/version/1.11.1) while it's hot!
