### ISSUE TITLE
Having issues with incompatible mod set? (using fabric mac)

### ISSUE THREAD

**Issue by lplp32** [RandomMcSomethin/fallingleaves#37]
I have optifabric, fabric api, optifine, cloth-config version 8.2.88, and falling leaves installed, but I keep getting this error message. 
![image](https://user-images.githubusercontent.com/113798732/190872531-fe3a718d-7776-4608-87e3-7d8587e6c00d.png)
`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config, version 7.0.0 or later.
Unmet dependency listing:
	 - Mod 'Falling Leaves' (fallingleaves) 1.12.2+1.19.2 requires version 7.0.0 or later of cloth-config, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

**Comment by lplp32** [comment]
Fixed
